/**
 * Source for the small inspector runtime embedded in a generated renderer.
 * This stays framework-agnostic and is kept separate from host route assembly.
 */
export function buildRendererInspectorRuntimeSource(): string {
  return [
    'const MAX_INSPECTOR_TREE_NODES = 4000;',
    'const MAX_INSPECTOR_TREE_DEPTH = 60;',
    'const MAX_INSPECTOR_TREE_CHILDREN = 256;',
    'const MAX_INSPECTOR_STRING = 4096;',
    'const MAX_INSPECTOR_NODE_STRING = 512;',
    'const MAX_INSPECTOR_OWNER_HINTS = 8;',
    'const MAX_INSPECTOR_COORDINATE = 10000000;',
    // Keep component-frame inspection chrome in lockstep with the regular
    // Preview's select script: blue 1.5px overlays for both hover and the
    // selected element, rather than the old green selection treatment.
    'const INSPECTOR_HOVER_BORDER = "1.5px solid #007DF0";',
    'const INSPECTOR_SELECTION_BORDER = "1.5px solid rgba(0,125,240,.95)";',
    'type RendererRoot = { tag: string; classTokens: string[]; id: string | null; source: { file: string; start: number; end: number; line: number; column: number; contentHash: string } };',
    'type RendererFrame = { frameId: string; componentId: string; generation: number; sessionId: string };',
    'type SourceRange = { file: string; start: number; end: number; contentHash: string };',
    'type MarkedElement = { element: Element; source: SourceRange };',
    'type InspectorTreeNode = { i: number; t: string; c: string; x: string; k: InspectorTreeNode[]; a?: string; o?: Array<Record<string, string | number>>; r?: string | null };',
    'let inspectorTreeIds = new WeakMap<Element, number>();',
    'let inspectorTreeById = new Map<number, Element>();',
    'let inspectorTreeNextId = 1;',
    'let inspectorTreeOn = false;',
    'let inspectorTreeObserver: MutationObserver | null = null;',
    'let inspectorTreeTimer: number | null = null;',
    'let inspectorRectCleanup: (() => void) | null = null;',
    'let inspectorHoverOverlay: HTMLDivElement | null = null;',
    'let inspectorSelectionOverlay: HTMLDivElement | null = null;',
    'let inspectorLastHoverId: number | null | undefined;',
    'let inspectorPost: (type: string, extra?: Record<string, unknown>) => void = () => undefined;',
    'let inspectorSelectedRef: { current: Element | null } = { current: null };',
    'let inspectorBaselineClassRef: { current: string | null } = { current: null };',
    'let inspectorBaselineElementRef: { current: Element | null } = { current: null };',
    'let inspectorPreviewStylesRef: { current: Map<string, string | null> } = { current: new Map() };',
    'let inspectorCascadeActiveRef: { current: boolean } = { current: false };',
    'function inspectorSetCascadeActive(requested: unknown): void { inspectorCascadeActiveRef.current = inspectorCascadeActiveRef.current || requested === true; }',
    'function inspectorResetCascadeActive(): void { inspectorCascadeActiveRef.current = false; }',
    'let inspectorTextEditing = false;',
    'let inspectorTextElement: HTMLElement | null = null;',
    'let inspectorTextRealElement: HTMLElement | null = null;',
    'let inspectorTextOriginalValue = "";',
    'let inspectorTextPreviousVisibility = "";',
    'let inspectorTextCloned = false;',
    // Component frames are inspection-only until the host explicitly proves
    // the selected source target and enables Edit main. Preview keeps its own
    // legacy bridge; this runtime must never optimistically mutate React DOM.
    'let inspectorTextEditable = false;',
    'let inspectorTextPending: { clone: HTMLElement; real: HTMLElement; previousVisibility: string; text: string; observer: MutationObserver | null; timer: number | null } | null = null;',
    'let inspectorTextRevertElement: HTMLElement | null = null;',
    'let inspectorTextRevertHtml = "";',
    'let inspectorStructureShortcuts = false;',
    '',
    'function boundedInspectorString(value: unknown, max = MAX_INSPECTOR_STRING): string { return typeof value === "string" ? value.slice(0, max) : ""; }',
    'function classTokens(element: Element): string[] { return (element.getAttribute("class") ?? "").split(/\\s+/).filter(Boolean).slice(0, 64); }',
    'function matchesRoot(element: Element, root: RendererRoot): boolean {',
    '  if (element.tagName.toLowerCase() !== root.tag) return false;',
    '  if ((element.getAttribute("id") ?? null) !== root.id) return false;',
    '  const actual = [...new Set(classTokens(element))].sort();',
    '  const expected = [...new Set(root.classTokens)].sort();',
    '  return actual.length === expected.length && actual.every((token, index) => token === expected[index]);',
    '}',
    'function domPath(element: Element): string {',
    '  const parts: string[] = []; let current: Element | null = element;',
    '  while (current && current.parentElement && parts.length < 16) {',
    '    const parent = current.parentElement; const index = Array.prototype.indexOf.call(parent.children, current);',
    '    parts.unshift(`${current.tagName.toLowerCase()}:${index}`); current = parent;',
    '  }',
    '  return parts.join("> ").replace(/> /g, ">").slice(0, 2048);',
    '}',
    'function ancestorClasses(element: Element): string[] {',
    '  const result: string[] = []; let current = element.parentElement;',
    '  while (current && result.length < 32) { const classes = current.getAttribute("class"); if (classes) result.push(classes.slice(0, 512)); current = current.parentElement; }',
    '  return result;',
    '}',
    'function selectionSignature(element: Element, root: RendererRoot) {',
    '  const text = (element.textContent ?? "").replace(/\\s+/g, " ").trim().slice(0, MAX_INSPECTOR_STRING);',
    '  return { tagName: element.tagName.toLowerCase().slice(0, 64), className: (element.getAttribute("class") ?? "").slice(0, MAX_INSPECTOR_STRING), ancestorClasses: ancestorClasses(element), ...(text ? { text } : {}), sourceFile: root.source.file.slice(0, 512), domPath: domPath(element) };',
    '}',
    'function inspectorTreeIdFor(element: Element): number {',
    '  const existing = inspectorTreeIds.get(element); if (existing) { inspectorTreeById.set(existing, element); return existing; }',
    '  const id = inspectorTreeNextId++; inspectorTreeIds.set(element, id); inspectorTreeById.set(id, element); return id;',
    '}',
    'function inspectorInternalNode(element: Element): boolean {',
    '  const tag = element.tagName.toUpperCase();',
    '  return tag === "SCRIPT" || tag === "STYLE" || tag === "NOSCRIPT" || tag === "TEMPLATE" || tag === "LINK" || tag === "META" || element.hasAttribute("data-ss-overlay") || element.hasAttribute("data-ss-internal") || /^ss[-_]/i.test(element.id);',
    '}',
    'function inspectorAllowedElement(root: Element | null, element: Element): boolean {',
    '  if (!root || !root.contains(element)) return false; let current: Element | null = element;',
    '  while (current) { if (inspectorInternalNode(current)) return false; if (current === root) break; current = current.parentElement; }',
    '  return true;',
    '}',
    'function inspectorOwnText(element: Element): string {',
    '  let value = ""; for (const child of Array.from(element.childNodes)) if (child.nodeType === Node.TEXT_NODE) value += child.nodeValue ?? "";',
    '  return value.replace(/\\s+/g, " ").trim().slice(0, 48);',
    '}',
    'function inspectorIsReactNode(element: Element): boolean { return Object.getOwnPropertyNames(element).some((key) => key.indexOf("__react") === 0); }',
    'const INSPECTOR_INLINE_TEXT_TAGS = new Set(["a", "b", "br", "code", "em", "i", "mark", "small", "span", "strong", "sub", "sup", "u"]);',
    'function inspectorEscapeAttribute(value: string): string { return value.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }',
    'function inspectorSerializeText(element: Element): string {',
    '  let output = ""; for (const child of Array.from(element.childNodes)) {',
    '    if (child.nodeType === Node.TEXT_NODE) output += child.nodeValue ?? "";',
    '    else if (child.nodeType === Node.ELEMENT_NODE) { const childElement = child as Element; const tag = childElement.tagName.toLowerCase(); if (!INSPECTOR_INLINE_TEXT_TAGS.has(tag)) continue; if (tag === "br") { output += "<br />"; continue; } const name = tag === "b" ? "strong" : tag === "i" ? "em" : tag; const attrs = Array.from(childElement.attributes).filter((attr) => attr.name !== "contenteditable" && !attr.name.startsWith("data-ss-")).map((attr) => ` ${attr.name}="${inspectorEscapeAttribute(attr.value)}"`).join(""); output += `<${name}${attrs}>${inspectorSerializeText(childElement)}</${name}>`; }',
    '  } return output.slice(0, MAX_INSPECTOR_STRING);',
    '}',
    'function inspectorTextCanEdit(element: Element | null): element is HTMLElement {',
    '  if (!(element instanceof HTMLElement) || !element.isConnected || inspectorInternalNode(element)) return false;',
    '  let hasText = false; const visit = (node: Node): boolean => { for (const child of Array.from(node.childNodes)) { if (child.nodeType === Node.TEXT_NODE) { if ((child.nodeValue ?? "").trim()) hasText = true; } else if (child.nodeType === Node.ELEMENT_NODE) { const childElement = child as Element; if (!INSPECTOR_INLINE_TEXT_TAGS.has(childElement.tagName.toLowerCase()) || inspectorInternalNode(childElement)) return false; if (!visit(childElement)) return false; } } return true; };',
    '  return visit(element) && hasText;',
    '}',
    'function inspectorTextTarget(node: EventTarget | Node | null): HTMLElement | null {',
    '  let element: Element | null = node instanceof Element ? node : node?.parentElement ?? null; let best: HTMLElement | null = null;',
    '  while (element && element !== document.body) { if (inspectorTextCanEdit(element)) best = element as HTMLElement; else if (best) break; element = element.parentElement; } return best;',
    '}',
    'function inspectorFinalizeTextPending(): void {',
    '  const pending = inspectorTextPending; if (!pending) return; inspectorTextPending = null;',
    '  pending.observer?.disconnect(); if (pending.timer !== null) window.clearTimeout(pending.timer);',
    '  pending.clone.remove(); pending.real.style.visibility = pending.previousVisibility; inspectorPlaceOverlay("selection", pending.real);',
    '}',
    'function inspectorStartText(element: HTMLElement): void {',
    '  if (inspectorTextEditing || !inspectorTextCanEdit(element) || !inspectorTextEditable) return;',
    '  inspectorFinalizeTextPending(); inspectorTextEditing = true; inspectorTextRealElement = element; inspectorTextCloned = inspectorIsReactNode(element); inspectorTextOriginalValue = inspectorSerializeText(element); let target = element;',
    '  if (inspectorTextCloned) {',
    '    const rect = element.getBoundingClientRect(); const clone = element.cloneNode(true) as HTMLElement; clone.removeAttribute("id"); clone.removeAttribute("data-ss-overlay"); clone.style.position = "absolute"; clone.style.left = `${rect.left + window.scrollX}px`; clone.style.top = `${rect.top + window.scrollY}px`; clone.style.width = `${rect.width}px`; clone.style.margin = "0"; clone.style.zIndex = "2147483646"; clone.style.animation = "none"; clone.style.transition = "none"; clone.setAttribute("data-ss-internal", "true"); document.body.appendChild(clone); inspectorTextPreviousVisibility = element.style.visibility; element.style.visibility = "hidden"; target = clone;',
    '  } else inspectorTextPreviousVisibility = "";',
    '  inspectorTextElement = target; target.setAttribute("contenteditable", "true"); target.setAttribute("data-ss-internal", "true"); target.focus(); inspectorPlaceOverlay("selection", null); inspectorPlaceOverlay("hover", target); inspectorPost("ss:textBegin");',
    '}',
    'function inspectorEndText(commit: boolean): void {',
    '  const target = inspectorTextElement; const real = inspectorTextRealElement; if (!target) return; const original = inspectorTextOriginalValue; const cloned = inspectorTextCloned; const text = inspectorSerializeText(target); const changed = commit && text.trim().length > 0 && text !== original; inspectorTextEditing = false; inspectorTextElement = null; inspectorTextRealElement = null; target.removeAttribute("contenteditable"); target.removeAttribute("data-ss-internal");',
    '  if (cloned && real) { if (!changed) { target.remove(); real.style.visibility = inspectorTextPreviousVisibility; inspectorPost("ss:textCancel"); } else { target.style.pointerEvents = "none"; const pending = { clone: target, real, previousVisibility: inspectorTextPreviousVisibility, text, observer: null as MutationObserver | null, timer: null as number | null }; inspectorTextPending = pending; try { pending.observer = new MutationObserver(() => { if (real.isConnected && inspectorSerializeText(real) === text) requestAnimationFrame(inspectorFinalizeTextPending); }); pending.observer.observe(real, { childList: true, subtree: true, characterData: true }); } catch { /* optional HMR bridge */ } pending.timer = window.setTimeout(inspectorFinalizeTextPending, 8000); inspectorPost("ss:textCommit", { text }); } } else if (real) { if (changed) { inspectorTextRevertElement = real; inspectorTextRevertHtml = real.innerHTML; inspectorPost("ss:textCommit", { text }); } else { inspectorPost("ss:textCancel"); } } inspectorPlaceOverlay("hover", null);',
    '}',
    'function inspectorSetTextEditable(editable: boolean): void { inspectorTextEditable = editable; if (!editable && inspectorTextEditing) { inspectorEndText(false); inspectorPost("ss:textBlocked"); } }',
    'function inspectorRevertText(): void { if (inspectorTextPending) inspectorFinalizeTextPending(); else if (inspectorTextRevertElement) { inspectorTextRevertElement.innerHTML = inspectorTextRevertHtml; inspectorPlaceOverlay("selection", inspectorTextRevertElement); } inspectorTextRevertElement = null; }',
    'function inspectorHandleTextKeydown(event: KeyboardEvent): void { if (!inspectorTextEditing) return; if ((event.metaKey || event.ctrlKey) && ["z", "y"].includes(event.key.toLowerCase())) { event.preventDefault(); try { document.execCommand(event.key.toLowerCase() === "z" && !event.shiftKey ? "undo" : "redo"); } catch { /* browser without execCommand */ } return; } if (event.key === "Escape") { event.preventDefault(); inspectorEndText(false); } else if (event.key === "Enter") { event.preventDefault(); inspectorEndText(event.metaKey || event.ctrlKey); } }',
    'function inspectorSetStructureShortcuts(enabled: boolean): void { inspectorStructureShortcuts = enabled; }',
    'function inspectorHandleStructureShortcut(event: KeyboardEvent): void { if (!inspectorStructureShortcuts || inspectorTextEditing || event.defaultPrevented || event.isComposing || event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement || (event.target instanceof HTMLElement && event.target.isContentEditable)) return; const key = event.key.toLowerCase(); const modifier = (event.metaKey || event.ctrlKey) && !event.shiftKey && !event.altKey; const allowed = key === "backspace" || (modifier && ["c", "x", "v", "d"].includes(key)); if (!allowed) return; event.preventDefault(); inspectorPost("ss:elementShortcut", { key }); }',
    'function inspectorTreeBuild(element: Element, depth: number, budget: { n: number; truncated: boolean }): InspectorTreeNode | null {',
    '  if (budget.n >= MAX_INSPECTOR_TREE_NODES || depth > MAX_INSPECTOR_TREE_DEPTH || inspectorInternalNode(element)) { budget.truncated = true; return null; }',
    '  budget.n += 1; const children: InspectorTreeNode[] = []; const rawChildren = Array.from(element.children);',
    '  if (depth >= MAX_INSPECTOR_TREE_DEPTH && rawChildren.length) budget.truncated = true;',
    '  for (const child of rawChildren.slice(0, MAX_INSPECTOR_TREE_CHILDREN)) {',
    '    if (inspectorInternalNode(child)) continue;',
    '    const bounded = inspectorTreeBuild(child, depth + 1, budget); if (bounded) children.push(bounded);',
    '    if (budget.n >= MAX_INSPECTOR_TREE_NODES) { budget.truncated = true; break; }',
    '  }',
    '  if (rawChildren.length > MAX_INSPECTOR_TREE_CHILDREN) budget.truncated = true;',
    '  const idAttribute = element.getAttribute("id");',
    '  const runtimeKey = (element as Element & { __shipstudioRuntimeKey?: unknown }).__shipstudioRuntimeKey;',
    '  const node: InspectorTreeNode = { i: inspectorTreeIdFor(element), t: element.tagName.toLowerCase().slice(0, 64), c: (element.getAttribute("class") ?? "").slice(0, MAX_INSPECTOR_NODE_STRING), x: inspectorOwnText(element), k: children };',
    '  if (idAttribute) node.a = idAttribute.slice(0, MAX_INSPECTOR_NODE_STRING);',
    '  if (runtimeKey === null) node.r = null; else if (typeof runtimeKey === "string") node.r = runtimeKey.slice(0, MAX_INSPECTOR_NODE_STRING);',
    '  return node;',
    '}',
    'function inspectorTreeSend(root: Element): void {',
    '  if (!root.isConnected || inspectorInternalNode(root)) return;',
    '  // Rebuild the reverse map on every snapshot. IDs for detached nodes must never remain selectable.',
    '  inspectorTreeById = new Map<number, Element>(); const budget = { n: 0, truncated: false }; const tree = inspectorTreeBuild(root, 0, budget);',
    '  if (tree) inspectorPost("ss:tree", { tree, truncated: budget.truncated });',
    '}',
    'function inspectorTreeDirty(root: Element): void {',
    '  if (!inspectorTreeOn) return; if (inspectorTreeTimer !== null) window.clearTimeout(inspectorTreeTimer);',
    '  inspectorTreeTimer = window.setTimeout(() => { inspectorTreeTimer = null; if (inspectorTreeOn) { inspectorPost("ss:treeDirty"); inspectorReportSelectionRect(root); } }, 300);',
    '}',
    'function inspectorMutationIsRelevant(mutations: MutationRecord[]): boolean {',
    '  return mutations.some((mutation) => {',
    '    if (mutation.type === "characterData") return !(mutation.target.parentElement && inspectorInternalNode(mutation.target.parentElement));',
    '    if (mutation.target instanceof Element && inspectorInternalNode(mutation.target)) return false;',
    '    for (const node of Array.from(mutation.addedNodes).concat(Array.from(mutation.removedNodes))) if (node instanceof Element && !inspectorInternalNode(node)) return true;',
    '    return mutation.type === "attributes";',
    '  });',
    '}',
    'function inspectorTreeStart(root: Element): void {',
    '  inspectorTreeOn = true; inspectorTreeObserver?.disconnect(); inspectorRectCleanup?.(); if (inspectorTreeTimer !== null) window.clearTimeout(inspectorTreeTimer); inspectorTreeTimer = null;',
    '  inspectorTreeObserver = new MutationObserver((mutations) => { if (inspectorMutationIsRelevant(mutations)) inspectorTreeDirty(root); });',
    '  inspectorTreeObserver.observe(root, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ["class", "id", "style"] });',
    '  const report = () => inspectorReportSelectionRect(root); window.addEventListener("scroll", report, true); window.addEventListener("resize", report); inspectorRectCleanup = () => { window.removeEventListener("scroll", report, true); window.removeEventListener("resize", report); };',
    '}',
    'function inspectorTreeStop(): void {',
    '  inspectorTreeOn = false; inspectorTreeObserver?.disconnect(); inspectorTreeObserver = null; inspectorRectCleanup?.(); inspectorRectCleanup = null;',
    '  if (inspectorTreeTimer !== null) window.clearTimeout(inspectorTreeTimer); inspectorTreeTimer = null; inspectorTreeById = new Map<number, Element>(); if (inspectorHoverOverlay) inspectorPlaceOverlay("hover", null); inspectorLastHoverId = undefined;',
    '}',
    'function inspectorRect(element: Element): { top: number; left: number; width: number; height: number } | null {',
    '  const rect = element.getBoundingClientRect(); const values = [rect.top, rect.left, rect.width, rect.height];',
    '  if (values.some((value) => !Number.isFinite(value) || Math.abs(value) > MAX_INSPECTOR_COORDINATE)) return null;',
    '  return { top: rect.top, left: rect.left, width: Math.max(0, rect.width), height: Math.max(0, rect.height) };',
    '}',
    'function inspectorOverlay(kind: "hover" | "selection"): HTMLDivElement {',
    '  const current = kind === "hover" ? inspectorHoverOverlay : inspectorSelectionOverlay; if (current) return current;',
    '  const element = document.createElement("div"); element.setAttribute("data-ss-overlay", kind); element.setAttribute("data-ss-internal", "true");',
    '  Object.assign(element.style, { position: "fixed", pointerEvents: "none", boxSizing: "border-box", zIndex: "2147483646", border: kind === "hover" ? INSPECTOR_HOVER_BORDER : INSPECTOR_SELECTION_BORDER, background: "transparent" });',
    '  document.body.appendChild(element); if (kind === "hover") inspectorHoverOverlay = element; else inspectorSelectionOverlay = element; return element;',
    '}',
    'function inspectorPlaceOverlay(kind: "hover" | "selection", target: Element | null): void {',
    '  const overlay = inspectorOverlay(kind); const rect = target && target.isConnected ? inspectorRect(target) : null;',
    '  if (!rect) { overlay.style.display = "none"; return; }',
    '  Object.assign(overlay.style, { display: "block", top: `${rect.top}px`, left: `${rect.left}px`, width: `${rect.width}px`, height: `${rect.height}px` });',
    '}',
    'function inspectorClearOverlays(): void { inspectorHoverOverlay?.remove(); inspectorSelectionOverlay?.remove(); inspectorHoverOverlay = null; inspectorSelectionOverlay = null; }',
    'function inspectorHover(root: Element | null, target: Element | null): void {',
    '  const element = target && inspectorAllowedElement(root, target) ? target : null;',
    '  const nodeId = element ? inspectorTreeIdFor(element) : null; inspectorPlaceOverlay("hover", element); if (inspectorLastHoverId !== nodeId) { inspectorLastHoverId = nodeId; inspectorPost("ss:hover", { nodeId }); }',
    '}',
    'function inspectorReportSelectionRect(root: Element | null): void {',
    '  const selected = inspectorSelectedRef.current; if (!root || !selected || !selected.isConnected || !root.contains(selected)) { inspectorPlaceOverlay("selection", null); inspectorPost("ss:selRect", { rect: null }); return; }',
    '  inspectorPlaceOverlay("selection", selected); const rect = inspectorRect(selected); if (rect) inspectorPost("ss:selRect", { rect });',
    '}',
    'function inspectorClearClassPreview(element: Element): void {',
    '  if (inspectorBaselineClassRef.current !== null) element.setAttribute("class", inspectorBaselineClassRef.current);',
    '  if (element instanceof HTMLElement) for (const [property, value] of inspectorPreviewStylesRef.current) value === null ? element.style.removeProperty(property) : element.style.setProperty(property, value);',
    '  inspectorPreviewStylesRef.current.clear();',
    '}',
    'function inspectorSelect(domRoot: Element, metadataRoot: RendererRoot, element: Element, selectionRequestId?: string): void {',
    '  if (!inspectorAllowedElement(domRoot, element)) return;',
    '  const previous = inspectorSelectedRef.current; if (previous !== element) { if (previous) inspectorClearClassPreview(previous); inspectorBaselineElementRef.current = element; inspectorBaselineClassRef.current = element.getAttribute("class") ?? ""; } else if (inspectorBaselineElementRef.current !== element || inspectorBaselineClassRef.current === null) { inspectorBaselineElementRef.current = element; inspectorBaselineClassRef.current = element.getAttribute("class") ?? ""; }',
    '  inspectorSelectedRef.current = element;',
    '  inspectorPlaceOverlay("selection", element); const signature = selectionSignature(element, metadataRoot); const rect = inspectorRect(element);',
    '  // The root source range is a boundary, not a descendant location. The host resolves the selected signature against the indexed definition before any write.',
    '  const requestId = typeof selectionRequestId === "string" && selectionRequestId.length > 0 && selectionRequestId.length <= 128 ? selectionRequestId : undefined;',
    '  inspectorPost("ss:select", { signature, count: 1, leafText: inspectorTextCanEdit(element), nodeId: inspectorTreeIdFor(element), ...(requestId ? { selectionRequestId: requestId } : {}), ...(rect ? { rect } : {}) });',
    '  if (inspectorCascadeActiveRef.current) inspectorPost("ss:cascade", { rules: collectCascadeRules(element), nodeId: inspectorTreeIdFor(element) });',
    '  if (element === domRoot) inspectorPost("element-selection", { sourceRange: metadataRoot.source, signature });',
    '}',
    'function inspectorSelectNode(domRoot: Element, metadataRoot: RendererRoot, id: unknown, selectionRequestId?: string): void {',
    '  if (typeof id !== "number" || !Number.isSafeInteger(id) || id < 0) return; const element = inspectorTreeById.get(id);',
    '  if (!element || !element.isConnected || !inspectorAllowedElement(domRoot, element)) return; try { element.scrollIntoView({ block: "nearest" }); } catch { /* ignore browser differences */ } inspectorSelect(domRoot, metadataRoot, element, selectionRequestId);',
    '}',
    'function inspectorReselect(domRoot: Element, metadataRoot: RendererRoot, value: unknown): void {',
    '  if (!value || typeof value !== "object") return; const signature = value as { domPath?: unknown; tagName?: unknown; className?: unknown };',
    '  const candidates = [domRoot, ...Array.from(domRoot.querySelectorAll("*"))].filter((candidate) => inspectorAllowedElement(domRoot, candidate));',
    '  if (typeof signature.domPath === "string" && signature.domPath.length > 0) { const matches = candidates.filter((candidate) => domPath(candidate) === signature.domPath); if (matches.length === 1) inspectorSelect(domRoot, metadataRoot, matches[0]); return; }',
    '  if (typeof signature.tagName !== "string" || typeof signature.className !== "string") return;',
    '  const matches = candidates.filter((candidate) => candidate.tagName.toLowerCase() === signature.tagName!.toLowerCase() && (candidate.getAttribute("class") ?? "") === signature.className); if (matches.length === 1) inspectorSelect(domRoot, metadataRoot, matches[0]);',
    '}',
    'function inspectorHoverNode(root: Element | null, id: unknown): void {',
    '  const element = id === null ? null : typeof id === "number" && Number.isSafeInteger(id) ? inspectorTreeById.get(id) ?? null : null; inspectorHover(root, element);',
    '}',
    'function inspectorPointerTarget(root: Element | null, target: EventTarget | null): Element | null { return target instanceof Element && inspectorAllowedElement(root, target) ? target : null; }',
    'function inspectorDestroy(): void { inspectorTreeStop(); if (inspectorTextEditing) inspectorEndText(false); inspectorFinalizeTextPending(); if (inspectorSelectedRef.current) inspectorClearClassPreview(inspectorSelectedRef.current); inspectorClearOverlays(); inspectorSelectedRef.current = null; inspectorBaselineElementRef.current = null; inspectorBaselineClassRef.current = null; inspectorPreviewStylesRef.current.clear(); inspectorLastHoverId = undefined; inspectorTextEditable = false; inspectorStructureShortcuts = false; }',
  ].join('\n');
}
